// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManyToHistory(arg1) {
  return window['go']['desktop']['App']['AddManyToHistory'](arg1);
}

export function AddToHistory(arg1) {
  return window['go']['desktop']['App']['AddToHistory'](arg1);
}

export function AnalyzeCompass(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['AnalyzeCompass'](arg1, arg2, arg3);
}

export function BatchAnalyze(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['BatchAnalyze'](arg1, arg2, arg3);
}

export function ClearHistory() {
  return window['go']['desktop']['App']['ClearHistory']();
}

export function GetDefaultConfig() {
  return window['go']['desktop']['App']['GetDefaultConfig']();
}

export function GetFilesCount(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['GetFilesCount'](arg1, arg2, arg3);
}

export function GetHistoryDir() {
  return window['go']['desktop']['App']['GetHistoryDir']();
}

export function GetHistoryStats() {
  return window['go']['desktop']['App']['GetHistoryStats']();
}

export function LoadHistory() {
  return window['go']['desktop']['App']['LoadHistory']();
}

export function LoadHistoryItem(arg1) {
  return window['go']['desktop']['App']['LoadHistoryItem'](arg1);
}

export function LoadHistoryItems(arg1) {
  return window['go']['desktop']['App']['LoadHistoryItems'](arg1);
}

export function LoadHistoryMetadata() {
  return window['go']['desktop']['App']['LoadHistoryMetadata']();
}

export function PreviewRename(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['PreviewRename'](arg1, arg2, arg3);
}

export function RemoveTextFromFilenames(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['RemoveTextFromFilenames'](arg1, arg2, arg3);
}

export function SaveExportFile(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SaveExportFile'](arg1, arg2, arg3, arg4);
}

export function SaveHistory(arg1) {
  return window['go']['desktop']['App']['SaveHistory'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['desktop']['App']['SelectDirectory'](arg1);
}
