// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToHistory(arg1) {
  return window['go']['desktop']['App']['AddToHistory'](arg1);
}

export function AnalyzeCompass(arg1, arg2) {
  return window['go']['desktop']['App']['AnalyzeCompass'](arg1, arg2);
}

export function BatchAnalyze(arg1, arg2) {
  return window['go']['desktop']['App']['BatchAnalyze'](arg1, arg2);
}

export function ClearHistory() {
  return window['go']['desktop']['App']['ClearHistory']();
}

export function GetDefaultConfig() {
  return window['go']['desktop']['App']['GetDefaultConfig']();
}

export function GetHistoryDir() {
  return window['go']['desktop']['App']['GetHistoryDir']();
}

export function GetHistoryStats() {
  return window['go']['desktop']['App']['GetHistoryStats']();
}

export function LoadHistory() {
  return window['go']['desktop']['App']['LoadHistory']();
}

export function SaveHistory(arg1) {
  return window['go']['desktop']['App']['SaveHistory'](arg1);
}
