// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {analyzer} from '../models';

export function AddToHistory(arg1:desktop.HistoryItem):Promise<void>;

export function AnalyzeCompass(arg1:string,arg2:analyzer.AnalysisConfig):Promise<desktop.AnalysisResponse>;

export function BatchAnalyze(arg1:string,arg2:analyzer.AnalysisConfig):Promise<Array<desktop.AnalysisResponse>>;

export function ClearHistory():Promise<void>;

export function GetDefaultConfig():Promise<analyzer.AnalysisConfig>;

export function GetHistoryDir():Promise<string>;

export function GetHistoryStats():Promise<Record<string, any>>;

export function LoadHistory():Promise<Array<desktop.HistoryItem>>;

export function SaveHistory(arg1:Array<desktop.HistoryItem>):Promise<void>;
